### ISSUE TITLE
Error: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by lokemorrmor** [LuisMayo/ace-attorney-discord-bot#41]
I get error: Error: [WinError 2] The system cannot find the file specified: '8907046726746699
59.mp4'

**Comment by LuisMayo** [comment]
What were you trying when this happened?
Did it have any consequences(did the bot not output a video, did it stop working at all)?

Can you paste the whole output?

Thanks!

**Comment by lokemorrmor** [comment]
full error: 
```
HTTP Error 404: Not Found
HTTP Error 404: Not Found
Error: [WinError 2] The system cannot find the file specified
Error: [WinError 2] The system cannot find the file specified: '8907046726746699
59.mp4'
```
I was using the !render command and it said failed at generating video but it still created a folder with the "'890704672674669959" containing the video

**Comment by LuisMayo** [comment]
It probably is due to ffmpeg.
Do you have a working ffmpeg installation?

What happens if you type ffmpeg on a powershell or cmd?

Thanks!

**Comment by LuisMayo** [comment]
This issue is usually because of ffmpeg not being properly installed on the system
